[project]
name = "fbo"
version = "0.1.0"
description = "An attempt at Football Ontology"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "neo4j>=6.1.0",
    "polars>=1.37.1",
    "rdflib>=7.5.0",
]
